apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
spec:
  selector:
    matchLabels:
      app: customer-service
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
        - name: customer-service
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
          image: ${REPOSITORY_TAG}
          imagePullPolicy: Never
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/v2/ping
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: webapp

  ports:
    - name: http
      port: 80
      nodePort: 30080

  type: NodePort